@startuml
title Поток сканирования файловой системы

start
:Проверить корневой путь;
:Создать корневой FileNode;
:Запустить ограниченный пул потоков;
:Поставить корневой каталог в очередь;

while (Есть ожидающие каталоги?) is (да)
  :Поток читает каталог через os.scandir;
  if (Элемент является символической ссылкой?) then (да)
    :Пропустить элемент;
  else (нет)
    if (Элемент является каталогом?) then (да)
      if (Каталог исключен по имени, пути или типу ФС?) then (да)
        :Пропустить каталог до сканирования;
      else (нет)
        :Создать FileNode каталога;
        :Поставить дочерний каталог в очередь;
      endif
    else (нет)
      :Прочитать stat-метаданные;
      :Использовать занятые блоки, если доступны;
      :Создать FileNode файла;
      :Обновить счетчики прогресса;
    endif
  endif
endwhile (нет)

:Посчитать агрегированные размеры каталогов;
:Отсортировать дочерние элементы по убыванию размера;
:Вернуть дерево FileNode;
stop

@enduml
